name: Docs Deploy

on:
  push:
    branches: [main]
    paths:
      - "docs/**"

jobs:
  docs-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-extras --dev --locked

      - name: Deploy documentation
        run: make docs-deploy
